pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage('Git Clone') {
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: 'main']], 
                    userRemoteConfigs: [[url: 'https://github.com/AnasJeg/fuel-project.git']]])
                }
            }
        }
        
        stage('Build Authentification') {
            steps {
                script {
                    dir('flask_server') {
                        bat './mvnw clean install'
                    }
                }
            }
        }
        stage('Build Spring') {
            steps {
                script {
                    dir('fuel_spring_server') {
                       bat './mvnw clean install -DskipTests'
                    }
                }
            }
        }
        stage('SonarQube') {
            steps {
                script {
                dir('fuel_spring_server') {
                        bat 'mvn sonar:sonar'
                    }
                }
            }
        }
        stage('Build Docker Images') {
            steps {
                script {
                    bat 'docker-compose build'
                   
                }
            }
        }
        stage('Run') {
            steps {
             script {
            bat 'docker-compose up -d''
            }
        
    }}
}
}
