server:
  port: 8888
spring:
  application:
    name: fuel-gateway
    cloud:
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8010/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
